# to run in terminal $ make
CC = gcc
CFLAGS = -lm -Wall

# List all your .c (or .cpp or .cc) files here (source files, excluding header files)
SRC_CODE = driver.c lex.c

#################################

# default rule

lex: $(SRC_CODE)
